{"name": "Try to search -000575", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //a[contains(text(), 'MI-000575 Карнавальная ночь')]\n\n", "trace": "  File \"c:\\users\\user\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\behave\\model.py\", line 1456, in run\n    match.run(runner.context)\n  File \"c:\\users\\user\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\behave\\model.py\", line 1903, in run\n    self.func(context, *args, **kwargs)\n  File \"step_test.py\", line 66, in step\n    \"//%s[contains(text(), '%s')]\" % (tag, text))\n  File \"c:\\users\\user\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 855, in find_element\n    'value': value})['value']\n  File \"c:\\users\\user\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 308, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\user\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 194, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Given website \"https://www.mirkrestikom.ru/\"", "status": "passed", "start": 1518520515570, "stop": 1518520518124}, {"name": "Then clear element by id 'search_input'", "status": "passed", "start": 1518520518124, "stop": 1518520518473}, {"name": "Then insert by id 'search_input' '-000575'", "status": "passed", "start": 1518520518473, "stop": 1518520518644}, {"name": "Then push on button by id 'search_submit'", "status": "passed", "start": 1518520518645, "stop": 1518520520620}, {"name": "Then find element 'a' with text 'MI-000575 Карнавальная ночь'", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //a[contains(text(), 'MI-000575 Карнавальная ночь')]\n\n", "trace": "  File \"c:\\users\\user\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\behave\\model.py\", line 1456, in run\n    match.run(runner.context)\n  File \"c:\\users\\user\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\behave\\model.py\", line 1903, in run\n    self.func(context, *args, **kwargs)\n  File \"step_test.py\", line 66, in step\n    \"//%s[contains(text(), '%s')]\" % (tag, text))\n  File \"c:\\users\\user\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 855, in find_element\n    'value': value})['value']\n  File \"c:\\users\\user\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 308, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\user\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 194, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1518520520620, "stop": 1518520520639}], "attachments": [{"name": "screenshot", "source": "919e5485-9b99-45d0-bfcc-a68e0c1c1e39-attachment.png", "type": "image/png"}], "start": 1518520515567, "stop": 1518520520719, "uuid": "0e26cddc-2a0a-4953-b790-c888770d973a", "historyId": "03de4b3fbe4de65dad1623966d1b8dfe", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Checking search (step)"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}