{"name": "Try to search -000575", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //a[contains(text(), 'MI-000575 Карнавальная ночь')]\n\n", "trace": "  File \"c:\\users\\user\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\behave\\model.py\", line 1456, in run\n    match.run(runner.context)\n  File \"c:\\users\\user\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\behave\\model.py\", line 1903, in run\n    self.func(context, *args, **kwargs)\n  File \"step_test.py\", line 61, in step\n    \"//%s[contains(text(), '%s')]\" % (tag, text))\n  File \"c:\\users\\user\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 855, in find_element\n    'value': value})['value']\n  File \"c:\\users\\user\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 308, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\user\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 194, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Given website \"https://www.mirkrestikom.ru/\"", "status": "passed", "start": 1518158547668, "stop": 1518158549152}, {"name": "Then clear element by id 'search_input'", "status": "passed", "start": 1518158549152, "stop": 1518158549255}, {"name": "Then insert by id 'search_input' '-000575'", "status": "passed", "start": 1518158549256, "stop": 1518158549276}, {"name": "Then push on button by id 'search_submit'", "status": "passed", "start": 1518158549276, "stop": 1518158551512}, {"name": "Then find element 'a' with text 'MI-000575 Карнавальная ночь'", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //a[contains(text(), 'MI-000575 Карнавальная ночь')]\n\n", "trace": "  File \"c:\\users\\user\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\behave\\model.py\", line 1456, in run\n    match.run(runner.context)\n  File \"c:\\users\\user\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\behave\\model.py\", line 1903, in run\n    self.func(context, *args, **kwargs)\n  File \"step_test.py\", line 61, in step\n    \"//%s[contains(text(), '%s')]\" % (tag, text))\n  File \"c:\\users\\user\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 855, in find_element\n    'value': value})['value']\n  File \"c:\\users\\user\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 308, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\user\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 194, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1518158551512, "stop": 1518158551528}], "attachments": [{"name": "screenshot", "source": "ba143c2a-1b1d-4d6c-8abf-a130372b04ae-attachment.png", "type": "image/png"}], "start": 1518158547667, "stop": 1518158551606, "uuid": "223c1d60-933a-4462-8991-01b4a72f35e6", "historyId": "03de4b3fbe4de65dad1623966d1b8dfe", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Checking search (step)"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}